---
output: hugodown::md_document
# Documentation: https://sourcethemes.com/academic/docs/managing-content/

title: "쮻ata Science, estad칤stica, matem치tica?"
subtitle: ""
summary: ""
authors: [admin]
tags: [Data Science]
categories: []
date: 2020-11-22
lastmod: 2020-11-22
featured: false
draft: false

# Featured image
# To use, add an image named `featured.jpg/png` to your page's folder.
# Focal points: Smart, Center, TopLeft, Top, TopRight, Left, Right, BottomLeft, Bottom, BottomRight.
image:
  caption: "Photo by [BHASKER GUPTA](https://analyticsindiamag.com/)"
  focal_point: "Smart"
  preview_only: false
  placement: 5

# Projects (optional).
#   Associate this post with one or more of your projects.
#   Simply enter your project's folder or file name without extension.
#   E.g. `projects = ["internal-project"]` references `content/project/deep-learning/index.md`.
#   Otherwise, set `projects = []`.
projects: []
---

### !Hola!

Estuve pensando mucho tiempo en c칩mo iniciar un blog enfocado en data science y voy a tratar de dirigir el contenido con base en mi propia experiencia en el aprendizaje de estos temas. Estudi칠 ingenier칤a estad칤stica en pre grado, y vi como poco a poco comenz칩 a emerger los t칠rminos de data science, machine learning, deep learning, etc. Luego de transitar por muchas definiciones, debemos entender primero que estamos en la era del **Big Data**, donde esta se define con las 4V (variedad, velocidad, volumen y veracidad) y esta forma parte fundamental de la cuarta revoluci칩n industrial.

Una mayor capacidad de c치lculo computacional en la nube, el almacenamiento de datos y generaci칩n de los mismos a gran escala gracias al avance de las tecnolog칤as, requiere que nos detengamos a pensar en c칩mo podemos sacarle provecho a 칠ste desborde de datos. Los skills que ahora necesitamos para poder afrontar esta nueva era nunca antes vista, son los **conocimientos matem치ticos**, **estad칤sticos**, **programaci칩n y la capacidad de s칤ntesis e interpretabilidad.**

Existe un diluvio de informaci칩n de este tema, muchos yendo a la aplicaci칩n directa en las diversas herramientas estad칤sticas y de machine learning que existen, sea **R** o **Python** por mencionar las m치s populares, resaltando las habilidades de programaci칩n y de paquetes predefinidos para la tarea que se lleva a cabo. Pero si se quiere llevar con mayor responsabilidad el uso de esto, se debe dar la importancia a las piedras angulares en la que se apoyan los m칠todos que nos ayudan en el trabajo de un cient칤fico de datos, la estad칤stica y las matem치ticas.

Si bien la estad칤stica se remonta mucho tiempo atr치s, con el origen de las grandes civilizaciones, la inclusi칩n de la teor칤a de la probabilidad la convirti칩 en una ciencia por el siglo XVII con Galileo y despu칠s, con los conceptos de inferencia y de la teor칤a de Bayes tuvo una evoluci칩n constante. A finales del siglo XX nace el concepto de regresi칩n y correlaci칩n con Francis Galton, m치s adelante las ideas del muestreo, el dise침o experimental, la prueba de hip칩tesis, los procesos estoc치sticos, an치lisis multivariante, series de tiempo, estad칤stica no param칠trica, modelos no lineales, etc nos muestra que es una ciencia viva y en constante adaptaci칩n a los cambios de los paradigmas.

Dicho todo esto, ser un cient칤fico de datos no es solo usar una librer칤a predefinida de alguna herramienta estad칤stica o de ML, es reconocer que hay detr치s de todo eso. Si Francis Galton quisiera ser etiquetado hoy un cient칤fico de datos, tendr칤a que desarrollar los skills que seguramente tienes desarrollados, el de la **programaci칩n** y del **tratamiento y manejo de grandes bases de datos**. Espero que esta breve introducci칩n sea lo que buscabas, y me acompa침es al desarrollo de diversos temas que trataremos de abarcar de una manera concisa y que espero te ayude a resolver algunas dudas que nos surgen cuando comenzamos explorar los t칩picos de Data Science.

Y si quieres ser un data scientist, 쯈u칠 skills te faltan?
  
### Te parece 칰til? Considera compartirlo 游뗿


