---
# Documentation: https://sourcethemes.com/academic/docs/managing-content/
output: hugodown::md_document
title: "Jornada Avances en Métodos Estadísticos"
event: 
event_url:
location: "online"
address:
  street:
  city:
  region:
  postcode:
  country: "Colombia"
summary:
abstract:

# Talk start and end times.
#   End time can optionally be hidden by prefixing the line with `#`.
date: 2021-11-25T19:41:36-05:00
date_end: 2021-11-26T19:41:36-05:00
all_day: false

# Schedule page publish date (NOT talk date).
publishDate: 2021-09-19T19:41:36-05:00

authors: [admin]
tags: []

# Is this a featured talk? (true/false)
featured: false

# Featured image
# To use, add an image named `featured.jpg/png` to your page's folder. 
# Focal points: Smart, Center, TopLeft, Top, TopRight, Left, Right, BottomLeft, Bottom, BottomRight.
image:
  caption: ""
  focal_point: "smart"
  preview_only: false

# Custom links (optional).
#   Uncomment and edit lines below to show custom links.
# links:
# - name: Follow
#   url: https://twitter.com
#   icon_pack: fab
#   icon: twitter

# Optional filename of your slides within your talk's folder or a URL.
url_slides:

url_code:
url_pdf:
url_video:

# Markdown Slides (optional).
#   Associate this talk with Markdown slides.
#   Simply enter your slide deck's filename without extension.
#   E.g. `slides = "example-slides"` references `content/slides/example-slides.md`.
#   Otherwise, set `slides = ""`.
slides: ""

# Projects (optional).
#   Associate this post with one or more of your projects.
#   Simply enter your project's folder or file name without extension.
#   E.g. `projects = ["internal-project"]` references `content/project/deep-learning/index.md`.
#   Otherwise, set `projects = []`.
projects: []
---
<div style="text-align: justify">

Conscientes de la importancia de la difusión de los avances en el desarrollo de métodos estadísticos, el Instituto Interamericano de Estadística (IASI), la Sociedad Colombiana de Estadística (SCE)  y la Universidad Nacional de Colombia, Sede Medellín, se han unido para realizar la Jornada Avances en Métodos Estadísticos. 

El evento se llevará a cabo de forma virtual los días 25 y 26 de noviembre de 2021 y en cada uno de los dos días, en el horario de 9:00 a 12 m, se dictarán tres conferencias relacionadas con los avances en métodos estadísticos para el análisis de datos como: el aprendizaje estadístico (statistical learning), modelos mixtos para datos longitudinales, estadística bayesiana, estadística industrial y estadísticas oficiales: análisis de series de tiempo oficiales y análisis multivariado de estadísticas oficiales. En horas de la tarde, entre las 14:00 y las 17:30, se realizará una sesión de ponencias donde se expondrán resultados de investigaciones a nivel teórico y aplicado, enmarcadas en los métodos estadísticos.

Mayor información en el [link](http://eventos.sce.org.co/?fbclid=IwAR2WUnif3ciVLQikI7yVwUmKlWjgHHhlKVlwQWf4ZqkJkVHYsTM2CAz_ipM)

<div/>

### Te parece útil? Considera compartirlo 🙌
